"""
diffusion_decoder: implements the Diffusion-powered decoder, introduced in the DALL·E 2 paper: https://cdn.openai.com/papers/dall-e-2.pdf

Description and Purpose:
    - There are two components/models in DALL·E 2 that work together:
        1. A prior generates CLIP image embeddings given a text caption/prompt.
        2. A decoder generates an image conditioned on the image embedding generated by the prior.
    - This Python file implements the decoder.

    - 

    - The decoder prior is explained in the paper, and in my notes: https://github.com/spencer-karofsky/aws_diffusion_model/blob/main/dall-e-2/notes/DALL-E-2%202022.pdf

"""